baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "OLLYEE"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/e78hkhprb.png", "img/9839953b2b1ad6c9feb28ac9689f9560-1-.jpg"]